version: '2'
services:
    filebeat-worker:
        image: prima/filebeat:5
        container_name: osdr-imaging-filebeat-worker
        volumes:
        - ./Logging/filebeat-worker/filebeat.yml:/filebeat.yml
        - ./Sds.Imaging.Worker/bin/Debug:/logs/
        networks:
        - docker_elk
        depends_on:
        - logstash
    filebeat-webapi:
        image: prima/filebeat:5
        container_name: osdr-imaging-filebeat-webapi
        volumes:
        - ./Logging/filebeat-webapi/filebeat.yml:/filebeat.yml
        - ./Sds.Imaging.WebApi:/logs/
        networks:
        - docker_elk
        depends_on:
        - logstash
    logstash:
        image: logstash
        container_name: osdr-imaging-logstash
        command: -f /config-dir/logstash.conf
        ports:
        - "5044:5044"
        - "5045:5045"
        - "12201:12201"
        - "12201:12201/udp"
        - "12202:12202"
        - "12202:12202/udp"
        volumes:
        - ./Logging/logstash:/config-dir
        - ./Logging/logstash/patterns:/opt/logstash/patterns_extra
        networks:
        - docker_elk
        depends_on:
        - elasticsearch
    kibana:
        image: kibana
        container_name: osdr-imaging-kibana
        environment:
        - ELASTICSEARCH_URL:"elasticsearch:9200"
        ports:
        - "5601:5601"
        networks:
        - docker_elk
        depends_on:
        - elasticsearch
    elasticsearch:
        image: elasticsearch
        container_name: osdr-imaging-elasticsearch
        environment:
        - ES_JAVA_OPTS:"-Des.path.conf=/etc/elasticsearch"
        volumes:
        - ./Logging/elasticsearch/data:/usr/share/elasticsearch/data
        ports:
        - "9200:9200"
        networks:
        - docker_elk
networks:
    docker_elk:
        driver: bridge